# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['conference_name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=20)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='nhlinfo.Conference')),
            ],
            options={
                'ordering': ['division_name'],
            },
        ),
    ]
