# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhlinfo', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('defense_id', models.AutoField(primary_key=True, serialize=False)),
                ('defense_abv', models.CharField(max_length=3)),
                ('defense_fname', models.CharField(max_length=25)),
                ('defense_lname', models.CharField(max_length=25)),
                ('defense_wt', models.FloatField(blank=True, default=None, null=True)),
                ('defense_ht', models.FloatField(blank=True, default=None, null=True)),
                ('defense_ga', models.IntegerField(blank=True, default=None, null=True)),
                ('defense_toi', models.FloatField(blank=True, default=None, null=True)),
                ('defense_nat', models.CharField(max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defenders', to='nhlinfo.Team')),
            ],
            options={
                'ordering': ['defense_lname', 'defense_fname', 'defense_abv'],
            },
        ),
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('forward_id', models.AutoField(primary_key=True, serialize=False)),
                ('forward_abv', models.CharField(max_length=3)),
                ('forward_fname', models.CharField(max_length=25)),
                ('forward_lname', models.CharField(max_length=25)),
                ('forward_wt', models.FloatField(blank=True, default=None, null=True)),
                ('forward_ht', models.FloatField(blank=True, default=None, null=True)),
                ('forward_pts', models.IntegerField(blank=True, default=None, null=True)),
                ('forward_toi', models.FloatField(blank=True, default=None, null=True)),
                ('forward_nat', models.CharField(max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forwards', to='nhlinfo.Team')),
            ],
            options={
                'ordering': ['forward_lname', 'forward_fname', 'forward_abv'],
            },
        ),
        migrations.CreateModel(
            name='Goalie',
            fields=[
                ('goalie_id', models.AutoField(primary_key=True, serialize=False)),
                ('goalie_abv', models.CharField(max_length=3)),
                ('goalie_fname', models.CharField(max_length=25)),
                ('goalie_lname', models.CharField(max_length=25)),
                ('goalie_wt', models.FloatField(blank=True, default=None, null=True)),
                ('goalie_ht', models.FloatField(blank=True, default=None, null=True)),
                ('goalies_ga', models.IntegerField(blank=True, default=None, null=True)),
                ('goalies_sp', models.IntegerField(blank=True, default=None, null=True)),
                ('goalies_nat', models.CharField(max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goalies', to='nhlinfo.Team')),
            ],
            options={
                'ordering': ['goalie_lname', 'goalie_fname', 'goalie_abv'],
            },
        ),
    ]
