# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-06 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlinfo', '0003_defense_forward_goalie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='goalies_ga',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='goalies_nat',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='goalies_sp',
        ),
        migrations.AddField(
            model_name='goalie',
            name='goalie_ga',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='goalie',
            name='goalie_nat',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='goalie',
            name='goalie_sp',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='goalie_abv',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='goalie_fname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='goalie_ht',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='goalie_lname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='goalie_wt',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
