# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-06 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhlinfo', '0004_goalie_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='team',
        ),
    ]
