# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-06 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhlinfo', '0006_goalie_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='team',
        ),
    ]
