# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlinfo', '0007_remove_defense_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defense',
            name='defense_ga',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='defense',
            name='defense_ht',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='defense',
            name='defense_toi',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='defense',
            name='defense_wt',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
