# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlinfo', '0012_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='defense_com',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='forward',
            name='forward_com',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='goalie_com',
            field=models.TextField(default=None, null=True),
        ),
    ]
